language: node_js

node_js:
  - "4.1"

before_script:
  - npm install -g gulp
  - npm install -g jspm
  - jspm install
  - pip install codecov

after_success:
  - codecov

script: gulp test --travis

